document.getElementsByClassName("sm-btn sm-btn-outlined sm-btn-rounded sm-btn-s")[0].innerHTML = "Uncalibrate Microphone";
document.getElementsByClassName("sm-btn sm-btn-outlined sm-btn-rounded sm-btn-s")[0].style.borderWidth = "thick";
document.getElementsByClassName("sm-btn sm-btn-outlined sm-btn-rounded sm-btn-s")[1].innerHTML = "Proof we dont know how to grade you.";
document.getElementsByClassName("sm-btn sm-btn-outlined sm-btn-rounded sm-btn-s")[1].style.borderWidth = "thick";
document.getElementsByClassName("sm-btn sm-btn-outlined play-button sm-btn-rounded sm-btn-m")[0].innerHTML = "Practice(But it still won't help you if<br>we don't know how to grade you.)";
document.getElementsByClassName("sm-btn sm-btn-outlined play-button sm-btn-rounded sm-btn-m")[0].style.borderWidth = "thick";
document.getElementsByClassName("sm-btn sm-btn-outlined record-button sm-btn-rounded sm-btn-m")[0].innerHTML = "Pathway to a False 0%";
document.getElementsByClassName("sm-btn sm-btn-outlined record-button sm-btn-rounded sm-btn-m")[0].style.borderWidth = "thick";
document.getElementsByClassName("sm-appbar").appendChild(document.createElement("h1").appendChild(document.createTextNode("Welcome to DumbMusic!")));
document.getElementsByClassName("sm-appbar-content")[0].appendChild(document.createElement("h1").appendChild(document.createTextNode("Welcome to DumbMusic!")));
